/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Cake.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cake.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 2.062, -0.009]} scale={[1.933, 0.968, 1.933]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['cake des1']} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[-0.003, 2.907, -0.009]} scale={[1.933, 0.126, 1.933]} />
      <group position={[-0.003, 4.003, -0.009]} scale={[1.296, 0.649, 1.296]}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.012']} />
      </group>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[-0.003, 4.57, -0.009]} rotation={[Math.PI, -1.084, Math.PI]} scale={[1.296, 0.085, 1.296]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.013']} position={[-0.014, 0.857, 0]} scale={[2.386, 0.195, 2.386]} />
      <group position={[-3.787, 5.545, -2.894]} rotation={[0, 0.85, 0]} scale={[1.146, 1.308, 0.039]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['frame border']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.glass} />
      </group>
      <group position={[4.739, 6.72, 1.817]} rotation={[Math.PI, -1.19, Math.PI]} scale={[1.053, 1.202, 0.036]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['frame border']} />
      </group>
      <group position={[-3.846, 4.717, 2.214]} rotation={[-Math.PI, 1.104, -Math.PI]} scale={[1.096, 1.251, 0.037]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['frame border']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.glass} />
      </group>
      <group position={[4.103, 3.534, -2.635]} rotation={[0, -0.718, 0]} scale={[1.21, 1.382, 0.041]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['frame border']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.image1} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials.glass} />
      </group>
      <group position={[0.606, 0.832, 4.679]} rotation={[0, 0.16, 0]} scale={[1.185, 1.354, 0.04]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['frame border']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cake.glb')
