/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_model/Cake.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CakeModel(props) {
 const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/Cake.glb')
  const { actions } = useAnimations(animations, group)
   return (
     <group ref={group} {...props} dispose={null}>
       <group name="Scene">
         <group name="Cylinder" position={[-0.003, 2.062, -0.009]} scale={[1.933, 0.968, 1.933]}>
           <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Material.010']} />
           <mesh name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['Material.011']} />
           <mesh name="Cylinder001_3" geometry={nodes.Cylinder001_3.geometry} material={materials['cake des1']} />
         </group>
         <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[-0.003, 2.907, -0.009]} scale={[1.933, 0.126, 1.933]} />
         <group name="Cylinder002" position={[-0.002, 3.979, -0.008]} scale={[1.214, 0.608, 1.214]}>
           <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Material.010']} />
           <mesh name="Cylinder007_1" geometry={nodes.Cylinder007_1.geometry} material={materials['Material.011']} />
           <mesh name="Cylinder007_2" geometry={nodes.Cylinder007_2.geometry} material={materials['Material.012']} />
         </group>
         <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[-0.003, 4.57, -0.009]} rotation={[Math.PI, -1.084, Math.PI]} scale={[1.296, 0.085, 1.296]} />
         <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.013']} position={[-0.014, 0.857, 0]} scale={[2.386, 0.195, 2.386]} />
         <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Material.006']} position={[0, 4.952, 0]} scale={[1.008, 1.031, 1.008]} />
         <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.006']} position={[0, 3.12, 0]} scale={[1.584, 1.62, 1.584]} />
         <mesh name="Cone" geometry={nodes.Cone.geometry} material={materials.ICING} position={[0, 1.297, 2.245]} scale={0.155} />
         <mesh name="Cone002" geometry={nodes.Cone002.geometry} material={materials.ICING} position={[0, 1.297, -2.24]} scale={0.155} />
         <mesh name="Cone003" geometry={nodes.Cone003.geometry} material={materials.ICING} position={[2.238, 1.297, -0.01]} scale={0.155} />
         <mesh name="Cone004" geometry={nodes.Cone004.geometry} material={materials.ICING} position={[-2.238, 1.297, -0.018]} scale={0.155} />
         <mesh name="Cone005" geometry={nodes.Cone005.geometry} material={materials.ICING} position={[-1.498, 1.297, 1.671]} rotation={[0, -0.732, 0]} scale={0.155} />
         <mesh name="Cone006" geometry={nodes.Cone006.geometry} material={materials.ICING} position={[1.498, 1.297, -1.666]} rotation={[0, -0.732, 0]} scale={0.155} />
         <mesh name="Cone007" geometry={nodes.Cone007.geometry} material={materials.ICING} position={[1.674, 1.297, 1.488]} rotation={[0, -0.732, 0]} scale={0.155} />
         <mesh name="Cone008" geometry={nodes.Cone008.geometry} material={materials.ICING} position={[-1.652, 1.297, -1.508]} rotation={[0, -0.732, 0]} scale={0.155} />
         <group name="wall_frame" position={[-3.787, 5.545, -2.894]} rotation={[0, 0.85, 0]} scale={[1.146, 1.308, 0.039]}>
           <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['frame border']} />
           <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['Material.007']} />
           <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials.glass} />
         </group>
         <group name="wall_frame002" position={[4.739, 6.72, 1.817]} rotation={[Math.PI, -1.19, Math.PI]} scale={[1.053, 1.202, 0.036]}>
           <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.glass} />
           <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials['Material.005']} />
           <mesh name="Cube012_2" geometry={nodes.Cube012_2.geometry} material={materials['frame border']} />
         </group>
         <group name="wall_frame003" position={[-3.846, 4.717, 2.214]} rotation={[-Math.PI, 1.104, -Math.PI]} scale={[1.096, 1.251, 0.037]}>
           <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['frame border']} />
           <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials['Material.008']} />
           <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials.glass} />
         </group>
         <group name="wall_frame004" position={[4.103, 3.534, -2.635]} rotation={[0, -0.718, 0]} scale={[1.21, 1.382, 0.041]}>
           <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['frame border']} />
           <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials.image1} />
           <mesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials.glass} />
         </group>
         <group name="wall_frame005" position={[0.606, 0.832, 4.679]} rotation={[0, 0.16, 0]} scale={[1.185, 1.354, 0.04]}>
           <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['frame border']} />
           <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials.glass} />
           <mesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={materials['Material.009']} />
         </group>
         <group name="Cylinder005" position={[0, 5.329, 0]} scale={[0.063, 0.43, 0.063]}>
           <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Cylinder003_1.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder003_1.morphTargetInfluences} />
           <mesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials['Material.004']} morphTargetDictionary={nodes.Cylinder003_2.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder003_2.morphTargetInfluences} />
         </group>
         <mesh name="Sphere" animations={actions} geometry={nodes.Sphere.geometry} material={materials.fire} morphTargetDictionary={nodes.Sphere.morphTargetDictionary} morphTargetInfluences={nodes.Sphere.morphTargetInfluences} position={[0, 5.835, 0]} scale={0.037} />
       </group>
     </group>
  )
}

useGLTF.preload('./models/Cake.glb')
